const FETCH_ALL_RATINGS = "FETCH_ALL_RATINGS";
const CREATE_RATING = "CREATE_RATING";
const EDIT_RATING = "EDIT_RATING";
const DELETE_RATING = "DELETE_RATING";
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";

export {
    FETCH_ALL_RATINGS,
    CREATE_RATING,
    EDIT_RATING,
    DELETE_RATING,
    AUTHENTICATION,
    LOGOUT
}